### ISSUE TITLE
Fix IndexError in the genetic_algorithm.py when creating a new generation

### ISSUE THREAD

**Issue by gnypit** [gnypit/pyqkd#16]
While `debugging labyrinth_test.py`, in the `create_new_generation` method in the `Population` class there is a problem with the following loop:
```
"""Secondly, we create the new generation with children being a result od selection and crossover operators
        on the current population:"""
        new_generation = Generation(size=self.no_parents_pairs * 2, fitness_function=self.fit_fun)

        for pair in self.current_children[0].get('children'):
            new_generation.add_member(genome=pair[0])
            new_generation.add_member(genome=pair[1])
```
Error traceback:
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.2.4\plugins\python\helpers\pydev\pydevd.py", line 1535, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm 2023.2.4\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\jg\PycharmProjects\pyqkd\genal\labyrinth_test.py", line 370, in <module>
    main_pyqkd()
  File "C:\Users\jg\PycharmProjects\pyqkd\genal\labyrinth_test.py", line 366, in main_pyqkd
    test.run()
  File "C:\Users\jg\PycharmProjects\pyqkd\genal\genetic_algorithm.py", line 317, in run
    self.create_new_generation()
  File "C:\Users\jg\PycharmProjects\pyqkd\genal\genetic_algorithm.py", line 263, in create_new_generation
    for pair in self.current_children[0].get('children'):
                ~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
Fix it.

**Comment by gnypit** [comment]
The `current_parents` list was empty, and so the `children_candidates` list and `current_children` dict were too.

**Comment by alguiguilo098** [comment]
Hi @gnypit, how are you?
I'm trying to resolve this issue. Are you already working on it?

**Comment by gnypit** [comment]
Hi @alguiguilo098 - last week we had a visit at work from another research group, so I was quite preoccupied. Thanks for asking. How are you? :)

Yes, I tired resolving the issue, but I'm a little stuck. I'm wondering, how to reorganise classes in the [genetic_algorithm.py](https://github.com/gnypit/pyqkd/blob/b8596a708de018654fddd196e51576d6412bdcf4/genal/genetic_algorithm.py). My idea right now is to treat the genetic algorithm (right now with no multiprocessing) as an external class, which creates and operates on different instances of the `Generation` class: one, current generation (from which parents are selected) and couple of rival generations with children created with different selection and crossover operators. Each `Generation` class should operate on `Member` class'instances.

With multiprocessing in mind, I'd like to store info about the operators and fitness function as 'low' as possible.

Perhaps if we manage to implement these changes or come up with another structure, then it'll be easier to debug errors like to one in this issue. I admit I was learning how to program along the way, so at first I didn't have a good, scalable idea on how to implement the parallel genetic algorithm.

**Comment by gnypit** [comment]
@alguiguilo098 I don't know this library, I'll take a look - thanks!

As for the application of multiprocessing, I was thinking about creating a list of all the members from different rival generations and evenly distribute them between as many processes as the available cores allow, to compute the fitness in parallel. That's because originally my BB84 simulations took a lot of time to compute (their results where the fitness values), so I wanted to perform the simulations in parallel.

I commited (ef2f1479) an example here: https://github.com/gnypit/pyqkd/blob/ef2f1479bf5b4d9f4f5a9721753c45195e33ad9e/matrix_multiply_parallel.py

What is this idea of enabling the genetic algorithm to parallelize the creation of multiple processes? Could you explain this, please? I'm really interested in your opinion 😄

**Comment by alguiguilo098** [comment]
@gnypit joblib can It. you can pass list of members, and pass calculate fitness and Jobs numbers, can try It ?

**Comment by gnypit** [comment]
@alguiguilo098 sure, that's a great idea 😉 I'll just finish rebuilding methods in the `GeneticAlgorithm` class in the `new-classical-ga-structure` branch and pull the code into `main` - would that be okay?

**Comment by alguiguilo098** [comment]
yes
